language: node_js
node_js:
  - "node"
  - "lts/*"
  - "10" # To keep v10 support alive even when lts shifts to a later version
env:
  global:
    # CODACY_PROJECT_TOKEN
    - secure: uEAtiFXRBXBApNTWULgcIrJU1ZSgvURSGQFDU3nQg7aqRADYJONEaiPvHEgs5ye1w9vVxR5kZWe8OaTuPdSEB7/p6FXyZeCE2d4IqqtgYvHG3/ImDy6QqSWDFXKmsMHb2a2SweNXvZu1nTs5sGB9WlTpanp6z0UN3zw383CEbSRlqHtPZ3/1NkBA19KuIV7qjV7KSUnq7Med/XQtb9ctXAw45CigIsE3pGCjWLW8zjMIYM2whPKd//coQHPWkygRS/U1hhv+BODw2GXE29XUnhrOAMuwR46171H0CCtwFki6b0fict1mFsT0LFyckv1FpLI/yeLGnYr7MNmZ5cGLFu6Iua2U6ZSFcIDrycftjr6fza46RpJtZkdOM3aejAHFVw/MWw766NS3Ap3cuQKh835g5gz3H22e5/qGrDSKx2PVW4SXsmAi/7gQUSpwlNfdLpoi4zOHPzpGdZRcihn6iCnAxJdu2m5+itY3zJeh+v/8PVDBjs1TTmvCVaCUsn0jfY/Bvpw901Y69qMDtcbL7XFTI9liED54ibGSRmXUq74lyNOnxjY5JFgY1f/tG0f9JLyuvb7uBSQmf8RimbOXTBlYmFBhivTnx3GLhqAvOwUssbtGoqMGm5lfM2e/0YgIAivCb9PQVKCASUGIXlZHZebCE9S8jdMR+8MpamTfLJE=
    # GH_TOKEN (Github for semantic-release)
    - secure: "kTg1jZf3zf7NvIxF3RwEf1rn7czN7wviLyMvFh1+VLdub6xSeJKJVWOyKYwlkRke3f8LQckjtBw4LD6oyJAPlkm+1E8NAv+sj6wTZ32UwNVaI9mBt+9gfJ4wWVtDgUrl178syph8V/dCUatiMOpXqD7lV1SNRl1tQSdktae6hADwopqrIYzxmudfDnlPRGmz3hTeT+HQXSMwvzOs6gnCg+fyRUX8kys2Fc0M44anqLFJlNAgH6PvwAuWzfmpBWErfTQqJ06kt2wnCFqTvElA+Pjv6eCDigMcaKuXD6gDQAeQCJ3zJ/SCIQrh6zHX9SAEfLxjgv+gu1fIYc+pWC2Wpp/HsaHEunZnEF+3UDsmg6+K77SBPUxtm/66KET6+XAECaO0qs1U4+hm05Fd40GIhZMtq/aFo1Pc71qsoFmcoApX3ojRHUCdC4oYuTBfkMWUUkxTe1pjQrnCw0Sx+u7gwkiKnufWJxSKmp0QFDSsrmVmzqBBfa558vNCf98LAzwSEbqbRh5J7UIYUxVr3ULN2uLmCqL3s6JFZQFVBO2BHtQ4xqfhJWVy0JhcBUmPu6zRAzqT+nSiKecMEhn/cYsJYsFxUQ1GCP/J+9uryEakf2lW2KOME0iyHunG1uJyPky1w1Jz2ShYVBP02xFNAhd7bmXH2by0LDSk49MFpLnikt8="
    # NPM_TOKEN
    - secure: "XIlYhrIn5a2nCawky+1Wk1WK1mGlTWZUttVHDQ2H6C9Vf1QdZCZWw3Bvihf+6Rn/naErTyUZneWMyDMt06BckhBzeYEZnyQ7OWjc6S8KFhLIcxtxyBlM5DVCt4QUNMBWs24CjOjiNwlUd40KE+YhfyR6Zvq1arrzCsFHjOvm/us+k0kto2B7VS7oQxVhSO3XEJIc96j4W6D/5BkyUXdwBsVHoulokCmAKgKMWAATkwCqE/l3e1m4ItGvlfkme1Kc89KRQpl9/rCF6IVZa/xbPgLyeL03eYC9DKXN0hboY5oEy6O1jwGnGR1K5az+yqOwrAUY+wrHNTesvabd0Z45hqPOTgLBtfoRxf8jEpIZaXbsYKJ1CklA/wOHwS2eJSSveuv++RN7h2TiJ8QyDoq5y0vm6QVQTy89QTdHR68FlZEe8OP1pBd6rtmPsoYIFjcQZh7hYkLHsomWBYopWTHuxx18SSnVmxZYOkhyNy9I1m7iFLFRgPrRp0+ZOpS5PA7lHwZ9DRekRIvZyh/LXUoA6AqWPShSiXiH8xDkGf/LYP03Np/pHfr5vdUgTBir+1LGEAvl1Z0TBUWlX4DUUiwdcQGM+KZnRYqwKVl7PpU/oV277ajphCMKoC1g3anApQ4bMCn9e52TsPNIVnMcSqDd4iSSJ1s98BHbdXUbJaphDaY="
cache: yarn

after_success:
  - test "$TRAVIS_NODE_VERSION" = "lts/*" && yarn coverage-publish

jobs:
  include:
    - stage: test
      script:
        - echo "Running with node version $(node -v). TRAVIS_NODE_VERSION=$TRAVIS_NODE_VERSION"
        - yarn test
    # Define the release stage that runs semantic-release
    - stage: semantic-release & demo
      node_js: lts/*
      script:
        # build it so the necessary distributable files exist
        - yarn build
        # build demo
        - pushd .
        - cd ./example
        - yarn
        - yarn build
        # cleanup unnecessary files for gh-pages branch
        - rm -rfd ./node_modules
        - rm -rfd ./src
        - rm -f ./package.json
        - rm -f ./yarn.lock
        # test the demo locally:
        - TEST_URL=http://localhost:8080 yarn test
        # leave us in our default working directory
        - popd
      deploy:
        - provider: script
          skip_cleanup: true
          script:
            - ./node_modules/.bin/semantic-release
          on:
            # Override `deploy` default of master; semantic-release will decide which branches to deploy on!
            all_branches: true
        - provider: pages
          # see https://docs.travis-ci.com/user/deployment/pages/
          skip_cleanup: true
          github_token: $GH_TOKEN
          # keep_history off avoids wasting space in repo, but be careful to only target the gh-pages branch!
          keep_history: false
          local_dir: ./example
          target_branch: gh-pages
          on:
            #branch: master
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^(master|live-example-test)$
        - provider: script
          skip_cleanup: true
          script:
            - echo "testing prod deployment"
            - pushd .
            - cd ./example
            - TEST_URL="https://activescott.github.io/agentmarkdown/" yarn test
            # leave us in our default working directory
            - popd
